acirurgias/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('busers.urls')),
    path('', include('ccip.urls')),
    path('', include('dashboard.urls')),
]

ccip/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('quant', views.quant, name="quant"),
    path('add_surgery', views.add_surgery, name="add_surgery"),
    path('update_surgery/<surgery_id>', views.update_surgery, name="update_surgery"),
    path('add_implant', views.add_implant, name="add_implant"),
    path('stock', views.stock, name="stock"),
    path('delete_implant/<int:implant_id>', views.delete_implant, name="delete_implant"),
    path('update_implant/<int:implant_id>', views.update_implant, name="update_implant"),
    path('delete_surgery/<int:surgery_id>', views.delete_surgery, name="delete_surgery"),
    path('add_client', views.add_client, name="add_client"),
    path('client_list', views.client_list, name="client_list"),
    path('delete_client/<int:client_id>', views.delete_client, name="delete_client"),
    path('update_client/<int:client_id>', views.update_client, name="update_client"),
    
]

ccip/models.py
from django.db import models
from django.db.models.fields import CharField, DateTimeField, DateField
import datetime
from django.contrib.postgres.fields import ArrayField
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.



class Implant(models.Model):
    imp =[]
    sizes = ['4x5', '4x6', '5x5', '5x6', '6x5','6x6','3.5x8','3.5x10','3.5x11.5','3.5x13','3.5x15','4.3x8','4.3x10','4.3x11.5','4.3x13','4.3x15']
    types = ['Neodent Alvim CM', 'Neodent Drive CM',  'Neodent Titamax WS CM', 'Nobel Replace CM', 'SIN SWC CM', 'SIN Strong CM', 'SIN Unitite CM']
    SIZE_CHOICES = []
    TYPE_CHOICES = []
    

    for size in sizes:
        SIZE_CHOICES.append((str(size), str(size)))
    for type in types:
        TYPE_CHOICES.append((str(type), str(type)))

    user = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    size = models.CharField(max_length=30, choices=SIZE_CHOICES, default='3.5x8', unique=False)
    type = models.CharField(max_length=60, choices=TYPE_CHOICES, default='Neodent Alvim CM 3.5x8', unique=False)
    quantity = models.IntegerField(default=1, blank=False )

    def __str__(self):
        return  str(self.type + ' ' + self.size)

class Client(models.Model):
    gender_choices = [('Masculino', 'Masculino'),('Feminino', 'Feminino'), ('Outro', 'Outro')]

    user = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=80, null=False)
    birth_date = models.DateField(blank=True, null=True)
    phone = models.CharField(max_length=20, blank=True, null=True)
    obs = models.TextField(max_length=1000, blank=True)
    gender = models.CharField(max_length=50, blank=True, choices=gender_choices)

    def __str__(self):
        return str(self.full_name)

class Surgery(models.Model):
    imp =[]
    sizes = ['3.5x8','3.5x10','3.5x11.5','3.5x13','3.5x15','4.3x8','4.3x10','4.3x11.5','4.3x13','4.3x15']
    SIZE_CHOICES = []
    types = ['Neodent Alvim CM', 'Neodent Drive CM','Neodent Titamax WS CM', 'SIN SWC CM', 'SIN Strong CM', 'SIN Unitite CM']
    TYPE_CHOICES= []
    for type in types:
        TYPE_CHOICES.append((str(type), str(type)))

    for tipo in types:
        for size in sizes:
            impl = tipo + ' ' + size
            imp.append(impl)
    
    implantes = []
    for i in imp:
        impla = (str(i), str(i))
        implantes.append(impla)

    areaList = []
    ini = 11
    for i in range(11, 48):
        if i not in [19,20,29,30,39,40]:
            areaList.append((i, i))

    areas = map(tuple, areaList)
    for size in sizes:
        SIZE_CHOICES.append((str(size), str(size)))
    STAGE = {
        ('Espera', 'Espera'),
        ('Andamento', 'Andamento'), 
        ('Finalizado', 'Finalizado'), 
    }
    PMU = {
        ('Unitária', 'Unitária'),
        ('Múltipla', 'Múltipla'), 
        ('Protocolo', 'Protocolo'), 
    }
    today = datetime.date.today()
    date = today.strftime("%d/%m/%y")

    user = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    client = models.ForeignKey(Client, null=True, on_delete=models.SET_NULL)
    date = models.DateField( auto_now=False, default=date)
    quantity = models.PositiveIntegerField(default=0)
    implant_type = ArrayField(models.CharField(max_length=50, choices=TYPE_CHOICES))
    implant_size = ArrayField(models.CharField(max_length=50, choices=SIZE_CHOICES))
    area = ArrayField(models.CharField(max_length=50, choices=areaList))
    obs = models.TextField(blank=True, max_length=600)
    stage = models.CharField(max_length=50, choices=STAGE, default='Espera')
    pmu = models.CharField(max_length=20, choices=PMU, default='Unitária')

    def __str__(self):
        return str(self.client)



#
#prot = models.BooleanField(default=False)

ccip/views.py
from ccip.forms import ClientForm, ImplantForm, SurgeryForm
from django.shortcuts import render
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
from django.conf import settings
from .models import *

# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return render(request, 'busers/register.html')
    else:
        user = get_object_or_404(User, pk=request.user.id)
        u_email = User.objects.filter(pk = request.user.id).values_list('email', flat=True)[0]
        
        surgerys = Surgery.objects.all().filter(user = user).order_by("-date")
        n_surg = len(surgerys)
        n = 0
        for i in range(n_surg):
            n += surgerys[i].quantity
        if n > 0:
            ratio = n / n_surg
        else:
            ratio = 0

        return render(request, 'ccip/index.html', {'user': user,'u_email':u_email, 'surgerys': surgerys, 'n_surg': n_surg, 'n': n, 'ratio': round(ratio, 2)})

def quant(request):
    if not request.user.is_authenticated:
        return render(request, 'busers/register.html')
    else:
        if request.method == "GET":
            u_email = User.objects.filter(pk = request.user.id).values_list('email', flat=True)[0]
            return render(request, 'ccip/quant.html', {'u_email': u_email})
        if request.method == "POST":
            u_email = User.objects.filter(pk = request.user.id).values_list('email', flat=True)[0]
            user = get_object_or_404(User, pk=request.user.id)
            quant = request.POST['quant']
            if not quant or int(quant) <= 0:
                return redirect('quant')
            else:
                clients = Client.objects.filter(user = user).values('full_name')
                stageOpt = ['Espera','Andamento','Finalizado']
                return render(request, 'ccip/add_surgery.html', {'quant': quant, 'clients': clients, 'stageOpt': stageOpt,'u_email': u_email})

def add_surgery(request):
    if not request.user.is_authenticated:
        return render(request, 'busers/register.html')
    else:
        if request.method == 'GET':
            u_email = User.objects.filter(pk = request.user.id).values_list('email', flat=True)[0]
            return render(request, 'ccip/add_surgery.html', {'u_email': u_email} )
        else:
            u_email = User.objects.filter(pk = request.user.id).values_list('email', flat=True)[0]
            user = get_object_or_404(User, pk=request.user.id)
            client_name = request.POST['client']
            clients = Client.objects.filter(full_name = client_name)
            client = clients[0]
            date = request.POST['date']
            quantity = request.POST['quantity']
            obs = request.POST['obs']
            stage = request.POST['stage']
            prot = request.POST['prot']
            
            areaList = []
            typeList = []
            sizeList = []
            implanteList = []
            stock = list(Implant.objects.all().filter(user = user))
            
            for i in range(int(quantity)):
                j = i + 1

                type = request.POST['type' + str(j)]
                size = request.POST['size' + str(j)]
                
                areaList.append(request.POST['area' + str(j)])
                typeList.append(type)
                sizeList.append(size)
                implante = str(typeList[i]) + ' ' + str(sizeList[i])
                implanteList.append(implante)
                imp = list(Implant.objects.all().filter(user = user, type = type, size = size))
                
                if imp == []:
                    messages.warning(request, "Checar estoque de implantes.")
                    
                else:
                    quant = imp[0].quantity
                    
                    Implant.objects.filter(user = user, type = type, size = size).update(quantity = (quant - 1) )
                    impl = Implant.objects.filter(user = user, type = type, size = size)
                    if impl[0].quantity <= 0:
                        Implant.objects.filter(user = user, type = type, size = size).update(quantity = 0 )
                        
                        messages.warning(request, 'Checar estoque de implantes.')
                        
                
            
            user = get_object_or_404(User, pk=request.user.id)
            surgery = Surgery.objects.create(
                user = user,
                client = client,
                date = date,
                quantity = quantity,
                implant_type = typeList,
                implant_size = sizeList,
                obs = obs,
                area = areaList,
                stage = stage,
                pmu = prot
            )
            try:
                surgery.save()
            except:
                messages.error(request, "Erro ao cadastrar nova cirurgia.")
                return redirect('quant')
            messages.success(request, "Cirurgia adicionada com sucesso!")
            return redirect('index')

def update_surgery(request, surgery_id):
    if not request.user.is_authenticated:

        return render(request, 'busers/register.html',)
    else:
        if request.method == "GET":
            u_email = User.objects.filter(pk = request.user.id).values_list('email', flat=True)[0]
            u_email = User.objects.filter(pk = request.user.id).values_list('email', flat=True)[0]
            user = get_object_or_404(User, pk=request.user.id)
            surgery = Surgery.objects.get(user=user, pk=surgery_id)
            form = SurgeryForm(instance=surgery)
            types = surgery.implant_type
            sizes = surgery.implant_size
            areas = surgery.area
            
            return render(request, "ccip/update_surgery.html", {'form': form, 'types': types, 'sizes': sizes, 'areas': areas, 'u_email': u_email})
        else:
            areaList = []
            typeList = []
            sizeList = []
            
            user = get_object_or_404(User, pk=request.user.id)
            surgery = Surgery.objects.get(user=user, pk=surgery_id)
            client = request.POST['client']
            
            date = request.POST['date']
            quantity = request.POST['quantity']
            for i in range(int(quantity)):
                areaList.append(request.POST["area" + str(i+1)])
                typeList.append(request.POST["type" + str(i+1)])
                sizeList.append(request.POST["size" + str(i+1)])
            obs = request.POST['obs']
            stage = request.POST['stage']
            pmu = request.POST['pmu']

            
            surgery = Surgery.objects.filter(user=user, pk=surgery_id).update(date=date, client=client, quantity=quantity, area=areaList,implant_type=typeList, implant_size=sizeList, obs=obs, stage=stage, pmu=pmu)
            messages.success(request, 'Cirurgia atualizada com sucesso!')
            return redirect('index')

def delete_surgery(request, surgery_id):
    user = get_object_or_404(User, pk=request.user.id)
    surg = Surgery.objects.get(user = user, pk=surgery_id)
    surg.delete()
    return redirect('index')

def add_implant(request):
    if not request.user.is_authenticated:
        return render(request, 'busers/register.html')
    else:
        if request.method == "POST":
            user = get_object_or_404(User, pk=request.user.id)
            u_email = User.objects.filter(pk = request.user.id).values_list('email', flat=True)[0]
            type = request.POST['type']
            size = request.POST['size']
            quantity = request.POST['quantity']
            imp = list(Implant.objects.all().filter(user = user, type = type, size = size))
            if imp == []:
                messages.success(request, "Implante adicionado com sucesso!")
                Implant.objects.create(
                    user = user,
                    type = type,
                    size = size,
                    quantity = quantity
                )
            else:
                implant_to_update = Implant.objects.all().filter(user = user, type = type, size = size)
                add = implant_to_update[0].quantity
                implant_to_update.update(quantity = int(add) + int(quantity))
                messages.success(request, "Implante atualizado com sucesso!")
            return redirect('stock')
        else:
            u_email = User.objects.filter(pk = request.user.id).values_list('email', flat=True)[0]
            form = ImplantForm
            return render(request, "ccip/add_implant.html", {'form': form, 'u_email': u_email})

def stock(request):
    if not request.user.is_authenticated:
        return render(request, 'busers/register.html')
    else:
        if request.method == "GET":
            u_email = User.objects.filter(pk = request.user.id).values_list('email', flat=True)[0]
            user = get_object_or_404(User, pk=request.user.id)
            stock = Implant.objects.all().filter(user = user)
            return render(request, 'ccip/stock.html', {'stock': stock, 'u_email': u_email})

def delete_implant(request, implant_id):
    if not request.user.is_authenticated:
        return render(request, 'busers/register.html')
    else:
        user = get_object_or_404(User, pk=request.user.id)
        imp_to_delete = Implant.objects.get(user = user, pk = implant_id)
        imp_to_delete.delete()
        return redirect('stock')

def update_implant(request, implant_id):
    if not request.user.is_authenticated:
        return render(request, 'busers/register.html')
    else:
        if request.method == "GET":
            u_email = User.objects.filter(pk = request.user.id).values_list('email', flat=True)[0]
            user = get_object_or_404(User, pk=request.user.id)

templates/ccip/add_client.html
{% extends 'ccip/base.html' %}
{% block content %}
{% include 'partials/_navbar-in.html' %}
{% include 'partials/_alerts.html' %}
<div class="container h-100 pt-5">
    <div class="row h-100 justify-content-center align-items-center">
        <div class="col-10 col-md-8 col-lg-6">
            <form action="" method='POST'>
            {% csrf_token %}
                <p class="description"><b>Coloque no formulário os dados do implante.</b></p>
                <div class="pb-3">
                {{form.full_name.label}}
                {{form.full_name}}

                {{form.birth_date.label}}
                {{form.birth_date}}

                {{form.gender.label}}
                {{form.gender}}

                {{form.phone.label}}
                {{form.phone}}

                {{form.obs.label}}
                {{form.obs}}
                </div>
                <input type="submit" value="Submit" class="btn btn-secondary">
            </form>
        </div>
    </div>
</div>
{%endblock%}

templates/ccip/add_implant.html
{% extends 'ccip/base.html' %}
{% block content %}
{% include 'partials/_navbar-in.html' %}
{% include 'partials/_alerts.html' %}
<div class="container h-100 pt-5">
    <div class="row h-100 justify-content-center align-items-center">
        <div class="col-10 col-md-8 col-lg-6">
            <form action="" method='POST'>
            {% csrf_token %}
                <p class="description"><b>Coloque no formulário os dados do implante.</b></p>
                <div class="pb-3">
                    {{form.type.label}}:
                    {{form.type}}

                    {{form.size.label}}:
                    {{form.size}}

                    {{form.quantity.label}}:
                    
                    {{form.quantity}}
                </div>
                <input type="submit" value="Submit" class="btn btn-secondary">
            </form>
        </div>
    </div>
</div>
{%endblock%}

templates/ccip/add_surgery.html
{% extends 'busers/base.html' %}
{% block content %}
{% include 'partials/_navbar-in.html' %}
{% include 'partials/_alerts.html' %}

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>

<div class='container'>
   <h6 class="p-3">
   Nova Cirurgia
   </h6>
   <input type="number" required value={{quant}} hidden id="id_quantity">
   
   <form action="{% url 'add_surgery' %}" method="POST">
   {% csrf_token %} 
   <div class="form-group">
      <label for="client">Nome: </label>
      <select class="form-control" id="client" name='client'>
      {% for client in clients %}
      <option>{{client.full_name}}</option>
      {% endfor %}
      
      </select>
   </div>

   <div class="mb-3">
      <label for="date" class="form-label">Data:</label>
      <input type="date" class="form-control" id="date" name="date" required>
   </div>

   <div class="mb-3">
      <input type="number" class="form-control" id="val" value="{{quant}}" name="quantity" hidden>
   </div>

   <div id="form-div">
   </div>

   <div class="mb-3">
      <label for="obs" class="form-label">Observações:</label>
      <textarea class="form-control" id="obs" name="obs" rows="3"></textarea>
   </div>

   <div class="form-group">   
      <label for="client">Estágio: </label>
      <select class="form-control" id="stage" name='stage'>
      {% for option in stageOpt %}
      <option>{{option}}</option>
      {% endfor %}
      </select>
   </div>

   <div class="form-group">
   <label for="inlineFormCustomSelect">Tipo de Prótese: </label>
   <select class="custom-select mr-sm-2" id="inlineFormCustomSelect" name="prot">
        <option value="Unitária" selected>Unitária</option>
        <option value="Multipla">Multipla</option>
        <option value="Protocolo">Protocolo</option>
      </select>
   </div>

   <input type="submit" value="Submit" class="btn btn-secondary" />
</form>
<div>
{%block script%}

<script>
   
</script>
<script>
/*
$(document).ready(function() {
   var val = $('#val').val()
   $('#id_quantity').val(val)
   
   
})
*/
</script>



</script>


<script>
/*
function Value(){
   var formdiv = document.getElementById('form-div')
   var quant = document.getElementById('id_quantity').value
   console.log(quant)

   

   for (i = 0; i < quant; i++){
      
      formdiv.append('asd\n')
   }
}*/
</script>

<script>
$(document).ready(GetValue())
      
   function GetValue() {
      var quant = parseInt($("#id_quantity").val()) + 1
      if (quant > 9){
         return null
      }
      //crate area options
      var area = 11
      var areaoptions = []
      var areaoption = "<option value='11'> 11 </option>"
         for (var i = area; i < 49; i++) {
            if (i != 19 && i != 20 && i != 29 && i != 30 && i != 39 && i != 40) {
            areaoption = "<option value = '" + i + "'>"+i+"</option>"
            areaoptions.push(areaoption)
            }
         }
      //create brand options
      
      // create type options
      var typeList = ['Neodent Alvim CM', 'Neodent Drive CM', 'Neodent Titamax WS CM','Nobel Replace CM', 'SIN SWC CM', 'SIN Strong CM', 'SIN Unitite CM'] //if new type is needed add here and in models
      var tlen = typeList.length
      var typeoptions = []
      for (i = 0; i < tlen; i++) {
         var option = "<option value = '"+typeList[i]+"'>"+typeList[i]+"</option>"
         typeoptions.push(option)
      }
      // create dimensions options
      var sizeList = ['3.5x8', '3.5x10', '3.5x11.5', '3.5x13', '3.5x15', '4.3x8', '4.3x10', '4.3x11.5', '4.3x13', '4.3x15', '4x5', '4x6', '5x5', '5x6', '6x5','6x6'] // if new size is needed add here and in models
      var slen = sizeList.length
      var sizeoptions = []
      for (i = 0; i < slen; i++) {
         var option = "<option value = '"+sizeList[i]+"'>"+sizeList[i]+"</option>"
         sizeoptions.push(option)
      }


      
      
      var div = $("#form-div")
      div.empty()
      for (i = 1; i < quant; i++) {
         
         div.append('<label for="area'+i+'"> Implante '+i+': </label>');
         div.append('<select id="area'+i+'" type="text" name="area'+i+'" class="form-control" placeholder="Area" required/>');
         div.append('<select id="type'+i+'" name="type'+i+'" class="form-control" placeholder="Tamanho do implante" required/>');
         div.append('<select id="size'+i+'" name="size'+i+'" class="form-control" placeholder="Tamanho do implante" required/>');
         div.append('<br/>')

         document.getElementById('area'+i+'').innerHTML = areaoptions;
         document.getElementById('type'+i+'').innerHTML = typeoptions;
         document.getElementById('size'+i+'').innerHTML = sizeoptions;
      }
   }

</script>
{%endblock%}
{% endblock %}

templates/ccip/client_list.html
{% extends 'ccip/base.html' %}
{% block content %}
{% include 'partials/_navbar-in.html' %}
{% include 'partials/_alerts.html' %}



<table class="table table-striped table-bordered table-hover table-sm">
  <thead class="thead-dark">
    <tr>
      <th scope="col" style="text-align: center; vertical-align: middle;">Nome</th>
      <th scope="col" style="text-align: center; vertical-align: middle;">Telefone</th>
      <th scope="col" style="text-align: center; vertical-align: middle;">Data de nascimento</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  {% for client in clients %}
    <tr>
      <th scope="row" style="text-align: center; vertical-align: middle;">{{client.full_name}}</th>
      <td style="text-align: center; vertical-align: middle;">
      {{client.phone}}
      </td>
      <td style="text-align: center; vertical-align: middle;">
      {{client.birth_date|date:"d/m/Y" }}
      </td>
      <td style="text-align: center; vertical-align: middle;">
      <a href="{% url 'update_client' client.id %}"><button type="button" class="btn btn-success">Edit</button></a>
      <a href="{% url 'delete_client' client.id %}"><button type="button" class="btn btn-danger">Del</button></a>
      </td>
    </tr>
{% endfor %}
  </tbody>

</table>
{% endblock %}

templates/ccip/update_surgery.html
{% extends 'busers/base.html' %}
{% block content %}
{% include 'partials/_navbar-in.html' %}
{% include 'partials/_alerts.html' %}

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>

<div class='container p-3'>

    <h5>
    Update surgery...
    </h5>
    

    <form action="" method="POST">
    {% csrf_token %}
    <div class="mb-3">
    {{form.client.label}}:
    {{form.client}}
    </div>
   <div class="mb-3">
    {{form.date.label}}:
    </br>
    {{form.date}}
   </div>
      <div class="mb-3">
    {{form.quantity.label}}:
    </br>
    {{form.quantity}}
    </div>
    
 

    <div id="form-div">

    </div>
   <div class="mb-3">
    {{form.obs.label}}:
    {{form.obs}}
   </div>
   <div class="mb-3">
    {{form.stage.label}}:
    {{form.stage}}
   </div>
   <div class="mb-3">
    {{form.pmu.label}}:
    {{form.pmu}}
   </div>

    

    <input type="submit" value="Submit" class="btn btn-secondary" />
    
</form>
   {% with c=0 %}
   
   {% for type in types %}
   
    <input type="text" value="{{type}}" id="{{forloop.counter}}" hidden></input>
    {% endfor %}
    {%endwith%}


    {% with c=0 %}
   
   {% for area in areas %}
   
    <input type="text" value="{{area}}" class="{{forloop.counter}}" hidden></input>
    {% endfor %}
    {%endwith%}

        {% with c=0 %}
   
   {% for size in sizes %}
   
    <input type="text" value="{{size}}" class="size{{forloop.counter}}" hidden></input>
    {% endfor %}
    {%endwith%}

<div>
{%block script%}

<script>


$(document).ready(GetValue())


   function GetValue() {
      
      var quant = parseInt($("#id_quantity").val()) + 1
      if (quant > 9){
         return null
      }
      //crate area options
      var area = 11
      var areaoptions = []
      var areaoption = "<option value='11'> 11 </option>"
         for (var i = area; i < 49; i++) {
            if (i != 19 && i != 20 && i != 29 && i != 30 && i != 39 && i != 40) {
            areaoption = "<option value = '" + i + "'>"+i+"</option>"
            areaoptions.push(areaoption)
            }
         }
      
      // create type options
      var typeList = ['Neodent Alvim CM', 'Neodent Drive CM', 'Neodent Titamax WS CM','Nobel Replace CM', 'SIN SWC CM', 'SIN Strong CM', 'SIN Unitite CM']//if new type is needed add here and in models
      var tlen = typeList.length
      var typeoptions = []
      for (i = 0; i < tlen; i++) {
         var option = "<option value = '"+typeList[i]+"'>"+typeList[i]+"</option>"
         typeoptions.push(option)
      }
      console.log(typeoptions)
      // create dimensions options
      var sizeList = ['3.5x8', '3.5x10', '3.5x11.5', '3.5x13', '3.5x15', '4.3x8', '4.3x10', '4.3x11.5', '4.3x13', '4.3x15', '4x5', '4x6', '5x5', '5x6', '6x5','6x6'] // if new size is needed add here and in models
      var slen = sizeList.length
      var sizeoptions = []
      for (i = 0; i < slen; i++) {
         var option = "<option value = '"+sizeList[i]+"'>"+sizeList[i]+"</option>"
         sizeoptions.push(option)
      }

      var impOpt = []
      for (i = 0; i < tlen; i++){
         var impName = typeList[i]
         for (j = 0; j < slen; j++){
            var impSize = sizeList[j]
            var fullImp = impName + " " + impSize
            var option = "<option value = '"+fullImp+"'>"+fullImp+"</option>"
            impOpt.push(option)
         }
      }


      
      impval = []
      areaval = []
      sizeval = []
      var div = $("#form-div")
      div.empty()
      for (i = 1; i < quant; i++) {
         impval.push($("#"+i+"").val())
         areaval.push($("."+i+"").val())
         sizeval.push($(".size"+i+"").val())
         
         
         div.append('<label for="area'+i+'"> Implante '+i+': </label>');
         div.append('<select id="area'+i+'" type="text" name="area'+i+'" class="form-control" placeholder="Area"  required></select>');
         div.append('<select id="type'+i+'" name="type'+i+'" class="form-control" value="" required/>');
         div.append('<select id="size'+i+'" name="size'+i+'" class="form-control" value="" required/>');
         div.append('<br/>')

         areaoptions.unshift("<option value='"+areaval[i-1]+"'>"+areaval[i-1]+"</option>")
         typeoptions.unshift("<option value='"+impval[i-1]+"'>"+impval[i-1]+"</option>")
         sizeoptions.unshift("<option value='"+sizeval[i-1]+"'>"+sizeval[i-1]+"</option>")

         document.getElementById('area'+i+'').innerHTML = areaoptions;
         document.getElementById('type'+i+'').innerHTML = typeoptions;
         document.getElementById('size'+i+'').innerHTML = sizeoptions;
         
         areaoptions.shift()
         typeoptions.shift()
         sizeoptions.shift()
         


         //$("#type"+i+"" "option").filter(function() {
         //   return this.text == text1; 
         //   }).attr('selected', true);

         
         
      }
   }
   

</script>
<script>

</script>
{%endblock%}
{% endblock %}